bigquery_sandbox:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account-json
      project: "{{ env_var('DBT_ENV_SECRET_PROJECT_ID') }}"
      dataset: "dev"
      threads: 4 # Must be a value of 1 or greater

      # These fields come from the service account json keyfile
      keyfile_json:
        type: "{{ env_var('DBT_ENV_SECRET_TYPE') }}"
        project_id: "{{ env_var('DBT_ENV_SECRET_PROJECT_ID') }}"
        private_key_id: "{{ env_var('DBT_ENV_SECRET_PRIVATE_KEY_ID') }}"
        private_key: "{{ env_var('DBT_ENV_SECRET_PRIVATE_KEY') }}"
        client_email: "{{ env_var('DBT_ENV_SECRET_CLIENT_EMAIL') }}"
        client_id: "{{ env_var('DBT_ENV_SECRET_CLIENT_ID') }}"
        auth_uri: "{{ env_var('DBT_ENV_SECRET_AUTH_URI') }}"
        token_uri: "{{ env_var('DBT_ENV_SECRET_TOKEN_URI') }}"
        auth_provider_x509_cert_url: "{{ env_var('DBT_ENV_SECRET_AUTH_PROVIDER_X509_CERT_URL') }}"
        client_x509_cert_url: "{{ env_var('DBT_ENV_SECRET_CLIENT_X509_CERT_URL') }}"

    prod:
      type: bigquery
      method: service-account-json
      project: "{{ env_var('DBT_ENV_SECRET_PROJECT_ID') }}"
      dataset: "prod"
      threads: 4 # Must be a value of 1 or greater

      # These fields come from the service account json keyfile
      keyfile_json:
        type: "{{ env_var('DBT_ENV_SECRET_TYPE') }}"
        project_id: "{{ env_var('DBT_ENV_SECRET_PROJECT_ID') }}"
        private_key_id: "{{ env_var('DBT_ENV_SECRET_PRIVATE_KEY_ID') }}"
        private_key: "{{ env_var('DBT_ENV_SECRET_PRIVATE_KEY') }}"
        client_email: "{{ env_var('DBT_ENV_SECRET_CLIENT_EMAIL') }}"
        client_id: "{{ env_var('DBT_ENV_SECRET_CLIENT_ID') }}"
        auth_uri: "{{ env_var('DBT_ENV_SECRET_AUTH_URI') }}"
        token_uri: "{{ env_var('DBT_ENV_SECRET_TOKEN_URI') }}"
        auth_provider_x509_cert_url: "{{ env_var('DBT_ENV_SECRET_AUTH_PROVIDER_X509_CERT_URL') }}"
        client_x509_cert_url: "{{ env_var('DBT_ENV_SECRET_CLIENT_X509_CERT_URL') }}"

    pr:
      type: bigquery
      method: service-account-json
      project: "{{ env_var('DBT_ENV_SECRET_PROJECT_ID') }}"
      dataset: "pr_{{ var('schema_id') }}"
      threads: 4 # Must be a value of 1 or greater

      # These fields come from the service account json keyfile
      keyfile_json:
        type: "{{ env_var('DBT_ENV_SECRET_TYPE') }}"
        project_id: "{{ env_var('DBT_ENV_SECRET_PROJECT_ID') }}"
        private_key_id: "{{ env_var('DBT_ENV_SECRET_PRIVATE_KEY_ID') }}"
        private_key: "{{ env_var('DBT_ENV_SECRET_PRIVATE_KEY') }}"
        client_email: "{{ env_var('DBT_ENV_SECRET_CLIENT_EMAIL') }}"
        client_id: "{{ env_var('DBT_ENV_SECRET_CLIENT_ID') }}"
        auth_uri: "{{ env_var('DBT_ENV_SECRET_AUTH_URI') }}"
        token_uri: "{{ env_var('DBT_ENV_SECRET_TOKEN_URI') }}"
        auth_provider_x509_cert_url: "{{ env_var('DBT_ENV_SECRET_AUTH_PROVIDER_X509_CERT_URL') }}"
        client_x509_cert_url: "{{ env_var('DBT_ENV_SECRET_CLIENT_X509_CERT_URL') }}"